[project]
name = "mlx"
version = "0.1.0"
description = "MLX: A command-line machine learning workflow runner."
authors = [{ name = "Your Name", email = "raphael.alampay@gmail.com" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = [
    "click>=8.1.3",
    "rich>=13.7.0",
    "ultralytics @ git+https://github.com/ralampay/ultralytics"
]

[project.scripts]
mlx = "mlx.cli:main"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
