[project]
name = "mlx"
version = "0.1.0"
description = "MLX: A command-line machine learning workflow runner."
authors = [{ name = "Your Name", email = "raphael.alampay@gmail.com" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.10"
dependencies = [
    "matplotlib",
    "numpy",
    "opencv-python",
    "rich>=13.7.0",
    "scikit-learn",
    "torch",
    "torchvision",
    "tqdm"
]

[project.optional-dependencies]
object-detection-ultralytics = [
    "onnxruntime",
    "ultralytics @ git+https://github.com/ralampay/ultralytics"
]
object-detection-libreyolo = [
    "libreyolo[onnx] @ git+https://github.com/ralampay/libreyolo.git@release"
]
object-detection = [
    "onnxruntime",
    "ultralytics @ git+https://github.com/ralampay/ultralytics",
    "libreyolo[onnx] @ git+https://github.com/ralampay/libreyolo.git@release"
]
tracking = [
    "motmetrics>=1.4.0",
    "scipy>=1.10.0"
]
aws = [
    "boto3>=1.34.0",
    "PyYAML>=6.0.1"
]
nlp = [
    "pandas",
    "llama-cpp-python"
]
image-explainability = [
    "grad-cam"
]

[project.scripts]
mlx = "mlx.cli:main"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["mlx*"]

[tool.setuptools.package-data]
mlx = [".dockerignore"]
"mlx.modes.object_detection.aws" = ["Dockerfile"]
"mlx.modes.image_classification.aws" = ["Dockerfile"]
