"""Provider boundary for MLX adapter experiment orchestration."""
from typing import Any, Protocol


class AdapterExperimentBackend(Protocol):
    """Execute detector operations while retaining the existing study artifact contract.

    run_condition returns a metrics mapping and writes the condition's config and
    metrics under request.output / request.method_id(method) / f"seed-{seed}".
    Failures crossing this boundary should be actionable MLXUserError values.
    """
    def validate(self, request) -> None: ...
    def study_metadata(self, request) -> dict: ...
    def resolve_device(self, requested: str) -> Any: ...
    def verify_foundation(self, request) -> tuple[Any, dict]: ...
    def collect_environment(self, request, device) -> dict: ...
    def targets(self, model, request, method: str, registry) -> dict[str, int]: ...
    def run_condition(self, request, method: str, seed: int, dataset: dict,
                      foundation: dict, device, registry) -> dict: ...
    def release(self, device) -> None: ...
